### ISSUE TITLE
Issues for __second revision__ 

### ISSUE THREAD

**Issue by ScatteredDrifter** [ScatteredDrifter/Quasar-67#3]
the first release came with some issues. 
Those has been noted and ought to be solved for the next iteration. 
Namely this means :
- [ ] reset switches colliding with Plate 
- [ ] adding screws for **blocker**
- [ ] misc, design choices?

**Comment by Sturek** [comment]
I modified the plate to have holes above the reset switches, so that should be fixed.

The plate and blocker have also been modified for m3 screws and standoffs.

I would add one thing: it would be great, if the two top LEDs were lower, so you could put something on the PCB to block the light bleed. Right now you need to put it between case and PCB/plate.
